version: '3.8'

services:
#Flask
 web:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./:/app

#MySQL database
 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

#phpMyAdmin
 pma:
  depends_on:
  - mysqldb
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  restart: always
  ports:
    - '8080:80'
  environment:
    PMA_HOST: mysqldb

#Volumes
volumes:
  mysql:
  mysql_config:

# Manualy create network msql : docker network create mysqlnet 